### ISSUE TITLE
`RangeFrom` clone

### ISSUE THREAD

**Issue by sollyucko** [rust-num/num-iter#16]
It would be great to have a clone of [`RangeFrom`](https://doc.rust-lang.org/std/ops/struct.RangeFrom.html). It would allow for infinite iterators for types (such as [`BigUint`](https://docs.rs/num-bigint/*/num_bigint/struct.BigUint.html) and [`BigInt`](https://docs.rs/num-bigint/*/num_bigint/struct.BigInt.html)) with no `::MAX`, since that can't exist for them.

It would implement `Iterator` (and `Clone`), but not `DoubleEndedIterator`, since the iterator is infinite. It would require `T` to implement `Add<A, Output=A>` and `Clone`, but not `PartialOrd` or `ToPrimitive`, since it's infinite.

I can implement it and submit a PR if you want.

**Comment by cuviper** [comment]
That sounds reasonable. Could you also add a `RangeStepFrom`? These should also come with warnings about overflow behavior as in the standard `RangeFrom` -- while that doesn't matter for bigint, in general it could.

**Comment by sollyucko** [comment]
Yep and yep.

**Comment by sollyucko** [comment]
Submitted #18

**Comment by cuviper** [comment]
Closed by #18.
