### ISSUE TITLE
summing range is slow

### ISSUE THREAD

**Issue by protogrammer** [rust-num/num-iter#24]
`range_inclusive(BigUint::one(), n).sum::<BigUint>()` where **n** is `BigUint` is slow (probably linear) (and product is probably too)
Is it possible to fix it? I'm new to Rust, so I may not know something
Full code:
```rust
use std::io;
use num::BigUint;
use num::One;
use num::iter::range_inclusive;

fn main() {
  let mut buf = String::new();
  io::stdin().read_line(&mut buf).unwrap();
  match buf.strip_suffix("\n").unwrap_or(buf.as_str()).parse::<BigUint>() {
    Ok(n) => println!("{}", range_inclusive(BigUint::one(), n).sum::<BigUint>()),
    Err(err) => println!("{}", err),
  }
}
```

**Comment by cuviper** [comment]
Unfortunately, these generic iterators do a lot of cloning, which for `BigUint` means a lot of allocator activity.

If `n` is small enough, you can do a little better with a `u32` iterator like `(1u32..=n).map(BigUint::from)`. `BigUint` can also sum primitive integers directly, `(1u32..=n).sum::<BigUint>()`, and this works for `product` too -- then you'll only have an allocation for the accumulator.

That sum also has a closed form, which you should especially use if `n` is larger than `u32`: `(1..=n).sum() == n*(n+1)/2`.

**Comment by protogrammer** [comment]
Ok, but is it possible to use formula `n(n+1)/2` for method **sum** in range/range_inclusive to do them more similar to built-in ranges?

**Comment by cuviper** [comment]
The method comes from the `Iterator` trait:

```rust
    fn sum<S>(self) -> S
    where
        Self: Sized,
        S: Sum<Self::Item>,
    {
        Sum::sum(self)
    }
```

The ranges implement `Iterator`, but they have *no idea* what `S` will be, nor even if that follows the expected arithmetic rules. The only interface `S: Sum` affords is feeding an iterator in. And on the flip side, any given `S` implementing `Sum` has no idea about the contents of the incoming generic iterator, so it can't apply any series transformations like that. Maybe someday [specialization](https://rust-lang.github.io/rfcs/1210-impl-specialization.html) will let us transform specific cases, but that feature has been a long time coming, and still won't be soon.

The built-in ranges don't do anything special here, but LLVM is clever enough to see patterns like this and optimize them to a closed form, at least for simple types like the primitive integers. Unfortunately, `BigUint` adds enough complication that LLVM can't do huge reductions like that anymore.
